services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    container_name: keycloak
    command: start-dev
    ports:
      - "9095:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - keycloak-net
    volumes:
      - keycloak_data:/opt/keycloak/data

networks:
  keycloak-net:
    driver: bridge

volumes:
  keycloak_data:
